gxpand unpack 1Compressed_Source 2Uncompressed_Source
gxpand unpack 3Compressed_Target 4Uncompressed_Target
xcopy "2Uncompressed_Source\arobin_e,lz,arc\vehicle\arobin\arobin_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\arobin" /i /y
xcopy "2Uncompressed_Source\arobin_e,lz,arc\vehicle\arobin\arobin_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\arobin" /i /y
xcopy "2Uncompressed_Source\bbull_e,lz,arc\vehicle\bbull\bbull_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\bbull" /i /y
xcopy "2Uncompressed_Source\bbull_e,lz,arc\vehicle\bbull\bbull_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\bbull" /i /y
xcopy "2Uncompressed_Source\bfalcon_e,lz,arc\vehicle\bfalcon\bfalcon_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\bfalcon" /i /y
xcopy "2Uncompressed_Source\bfalcon_e,lz,arc\vehicle\bfalcon\bfalcon_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\bfalcon" /i /y
xcopy "2Uncompressed_Source\bfang_e,lz,arc\vehicle\bfang\bfang_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\bfang" /i /y
xcopy "2Uncompressed_Source\bfang_e,lz,arc\vehicle\bfang\bfang_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\bfang" /i /y
xcopy "2Uncompressed_Source\cbear_e,lz,arc\vehicle\cbear\cbear_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\cbear" /i /y
xcopy "2Uncompressed_Source\cbear_e,lz,arc\vehicle\cbear\cbear_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\cbear" /i /y
xcopy "2Uncompressed_Source\danc_e,lz,arc\vehicle\danc\danc_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\danc" /i /y
xcopy "2Uncompressed_Source\danc_e,lz,arc\vehicle\danc\danc_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\danc" /i /y
xcopy "2Uncompressed_Source\darks_e,lz,arc\vehicle\darks\darks_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\darks" /i /y
xcopy "2Uncompressed_Source\darks_e,lz,arc\vehicle\darks\darks_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\darks" /i /y
xcopy "2Uncompressed_Source\dclaw_e,lz,arc\vehicle\dclaw\dclaw_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\dclaw" /i /y
xcopy "2Uncompressed_Source\dclaw_e,lz,arc\vehicle\dclaw\dclaw_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\dclaw" /i /y
xcopy "2Uncompressed_Source\fats_e,lz,arc\vehicle\fats\fats_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\fats" /i /y
xcopy "2Uncompressed_Source\fats_e,lz,arc\vehicle\fats\fats_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\fats" /i /y
xcopy "2Uncompressed_Source\fsting_e,lz,arc\vehicle\fsting\fsting_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\fsting" /i /y
xcopy "2Uncompressed_Source\fsting_e,lz,arc\vehicle\fsting\fsting_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\fsting" /i /y
xcopy "2Uncompressed_Source\gfox_e,lz,arc\vehicle\gfox\gfox_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\gfox" /i /y
xcopy "2Uncompressed_Source\gfox_e,lz,arc\vehicle\gfox\gfox_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\gfox" /i /y
xcopy "2Uncompressed_Source\gpan_e,lz,arc\vehicle\gpan\gpan_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\gpan" /i /y
xcopy "2Uncompressed_Source\gpan_e,lz,arc\vehicle\gpan\gpan_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\gpan" /i /y
xcopy "2Uncompressed_Source\gstar_e,lz,arc\vehicle\gstar\gstar_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\gstar" /i /y
xcopy "2Uncompressed_Source\gstar_e,lz,arc\vehicle\gstar\gstar_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\gstar" /i /y
xcopy "2Uncompressed_Source\gtaxi_e,lz,arc\vehicle\gtaxi\gtaxi_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\gtaxi" /i /y
xcopy "2Uncompressed_Source\gtaxi_e,lz,arc\vehicle\gtaxi\gtaxi_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\gtaxi" /i /y
xcopy "2Uncompressed_Source\hhawk_e,lz,arc\vehicle\hhawk\hhawk_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\hhawk" /i /y
xcopy "2Uncompressed_Source\hhawk_e,lz,arc\vehicle\hhawk\hhawk_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\hhawk" /i /y
xcopy "2Uncompressed_Source\hspeed_e,lz,arc\vehicle\hspeed\hspeed_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\hspeed" /i /y
xcopy "2Uncompressed_Source\hspeed_e,lz,arc\vehicle\hspeed\hspeed_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\hspeed" /i /y
xcopy "2Uncompressed_Source\itiger_e,lz,arc\vehicle\itiger\itiger_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\itiger" /i /y
xcopy "2Uncompressed_Source\itiger_e,lz,arc\vehicle\itiger\itiger_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\itiger" /i /y
xcopy "2Uncompressed_Source\kmete_e,lz,arc\vehicle\kmete\kmete_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\kmete" /i /y
xcopy "2Uncompressed_Source\kmete_e,lz,arc\vehicle\kmete\kmete_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\kmete" /i /y
xcopy "2Uncompressed_Source\lwy_e,lz,arc\vehicle\lwy\lwy_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\lwy" /i /y
xcopy "2Uncompressed_Source\lwy_e,lz,arc\vehicle\lwy\lwy_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\lwy" /i /y
xcopy "2Uncompressed_Source\mgull_e,lz,arc\vehicle\mgull\mgull_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\mgull" /i /y
xcopy "2Uncompressed_Source\mgull_e,lz,arc\vehicle\mgull\mgull_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\mgull" /i /y
xcopy "2Uncompressed_Source\mhurr_e,lz,arc\vehicle\mhurr\mhurr_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\mhurr" /i /y
xcopy "2Uncompressed_Source\mhurr_e,lz,arc\vehicle\mhurr\mhurr_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\mhurr" /i /y
xcopy "2Uncompressed_Source\mty_e,lz,arc\vehicle\mty\mty_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\mty" /i /y
xcopy "2Uncompressed_Source\mty_e,lz,arc\vehicle\mty\mty_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\mty" /i /y
xcopy "2Uncompressed_Source\mwolf_e,lz,arc\vehicle\mwolf\mwolf_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\mwolf" /i /y
xcopy "2Uncompressed_Source\mwolf_e,lz,arc\vehicle\mwolf\mwolf_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\mwolf" /i /y
xcopy "2Uncompressed_Source\nthun_e,lz,arc\vehicle\nthun\nthun_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\nthun" /i /y
xcopy "2Uncompressed_Source\nthun_e,lz,arc\vehicle\nthun\nthun_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\nthun" /i /y
xcopy "2Uncompressed_Source\pinks_e,lz,arc\vehicle\pinks\pinks_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\pinks" /i /y
xcopy "2Uncompressed_Source\pinks_e,lz,arc\vehicle\pinks\pinks_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\pinks" /i /y
xcopy "2Uncompressed_Source\prabbit_e,lz,arc\vehicle\prabbit\prabbit_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\prabbit" /i /y
xcopy "2Uncompressed_Source\prabbit_e,lz,arc\vehicle\prabbit\prabbit_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\prabbit" /i /y
xcopy "2Uncompressed_Source\qmete_e,lz,arc\vehicle\qmete\qmete_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\qmete" /i /y
xcopy "2Uncompressed_Source\qmete_e,lz,arc\vehicle\qmete\qmete_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\qmete" /i /y
xcopy "2Uncompressed_Source\rainp_e,lz,arc\vehicle\rainp\rainp_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\rainp" /i /y
xcopy "2Uncompressed_Source\rainp_e,lz,arc\vehicle\rainp\rainp_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\rainp" /i /y
xcopy "2Uncompressed_Source\rgaze_e,lz,arc\vehicle\rgaze\rgaze_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\rgaze" /i /y
xcopy "2Uncompressed_Source\rgaze_e,lz,arc\vehicle\rgaze\rgaze_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\rgaze" /i /y
xcopy "2Uncompressed_Source\rrock_e,lz,arc\vehicle\rrock\rrock_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\rrock" /i /y
xcopy "2Uncompressed_Source\rrock_e,lz,arc\vehicle\rrock\rrock_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\rrock" /i /y
xcopy "2Uncompressed_Source\sang_e,lz,arc\vehicle\sang\sang_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\sang" /i /y
xcopy "2Uncompressed_Source\sang_e,lz,arc\vehicle\sang\sang_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\sang" /i /y
xcopy "2Uncompressed_Source\scarp_e,lz,arc\vehicle\scarp\scarp_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\scarp" /i /y
xcopy "2Uncompressed_Source\scarp_e,lz,arc\vehicle\scarp\scarp_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\scarp" /i /y
xcopy "2Uncompressed_Source\smoon_e,lz,arc\vehicle\smoon\smoon_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\smoon" /i /y
xcopy "2Uncompressed_Source\smoon_e,lz,arc\vehicle\smoon\smoon_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\smoon" /i /y
xcopy "2Uncompressed_Source\sphan_e,lz,arc\vehicle\sphan\sphan_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\sphan" /i /y
xcopy "2Uncompressed_Source\sphan_e,lz,arc\vehicle\sphan\sphan_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\sphan" /i /y
xcopy "2Uncompressed_Source\spira_e,lz,arc\vehicle\spira\spira_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\spira" /i /y
xcopy "2Uncompressed_Source\spira_e,lz,arc\vehicle\spira\spira_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\spira" /i /y
xcopy "2Uncompressed_Source\srat_e,lz,arc\vehicle\srat\srat_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\srat" /i /y
xcopy "2Uncompressed_Source\srat_e,lz,arc\vehicle\srat\srat_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\srat" /i /y
xcopy "2Uncompressed_Source\tnori_e,lz,arc\vehicle\tnori\tnori_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\tnori" /i /y
xcopy "2Uncompressed_Source\tnori_e,lz,arc\vehicle\tnori\tnori_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\tnori" /i /y
xcopy "2Uncompressed_Source\wboar_e,lz,arc\vehicle\wboar\wboar_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\wboar" /i /y
xcopy "2Uncompressed_Source\wboar_e,lz,arc\vehicle\wboar\wboar_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\wboar" /i /y
xcopy "2Uncompressed_Source\wcat_e,lz,arc\vehicle\wcat\wcat_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\wcat" /i /y
xcopy "2Uncompressed_Source\wcat_e,lz,arc\vehicle\wcat\wcat_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\wcat" /i /y
xcopy "2Uncompressed_Source\wgoose_e,lz,arc\vehicle\wgoose\wgoose_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\wgoose" /i /y
xcopy "2Uncompressed_Source\wgoose_e,lz,arc\vehicle\wgoose\wgoose_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\wgoose" /i /y
xcopy "2Uncompressed_Source\wwasp_e,lz,arc\vehicle\wwasp\wwasp_02.gma" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\wwasp" /i /y
xcopy "2Uncompressed_Source\wwasp_e,lz,arc\vehicle\wwasp\wwasp_sv0.tpl" "4Uncompressed_Target\vehicle_sel,lz,arc\vehicle\wwasp" /i /y
gxpand pack 4uncompressed_Target 5Final_Output

pause
