gxpand unpack 1CompressedSource 2Source
gxpand unpack 3CompressedTarget 4Target
xcopy "2Source\arobin_e,lz,arc\vehicle\arobin\arobin.fmi" "4Target\arobin_e,lz,arc\vehicle\arobin" /i /y
xcopy "2Source\arobin_p,lz,arc\vehicle\arobin\arobin.fmi" "4Target\arobin_p,lz,arc\vehicle\arobin" /i /y
xcopy "2Source\bbull_e,lz,arc\vehicle\bbull\bbull.fmi" "4Target\bbull_e,lz,arc\vehicle\bbull" /i /y
xcopy "2Source\bbull_p,lz,arc\vehicle\bbull\bbull.fmi" "4Target\bbull_p,lz,arc\vehicle\bbull" /i /y
xcopy "2Source\bfalcon_e,lz,arc\vehicle\bfalcon\bfalcon.fmi" "4Target\bfalcon_e,lz,arc\vehicle\bfalcon" /i /y
xcopy "2Source\bfalcon_p,lz,arc\vehicle\bfalcon\bfalcon.fmi" "4Target\bfalcon_p,lz,arc\vehicle\bfalcon" /i /y
xcopy "2Source\bfang_e,lz,arc\vehicle\bfang\bfang.fmi" "4Target\bfang_e,lz,arc\vehicle\bfang" /i /y
xcopy "2Source\bfang_p,lz,arc\vehicle\bfang\bfang.fmi" "4Target\bfang_p,lz,arc\vehicle\bfang" /i /y
xcopy "2Source\cbear_e,lz,arc\vehicle\cbear\cbear.fmi" "4Target\cbear_e,lz,arc\vehicle\cbear" /i /y
xcopy "2Source\cbear_p,lz,arc\vehicle\cbear\cbear.fmi" "4Target\cbear_p,lz,arc\vehicle\cbear" /i /y
xcopy "2Source\danc_e,lz,arc\vehicle\danc\danc.fmi" "4Target\danc_e,lz,arc\vehicle\danc" /i /y
xcopy "2Source\danc_p,lz,arc\vehicle\danc\danc.fmi" "4Target\danc_p,lz,arc\vehicle\danc" /i /y
xcopy "2Source\darks_e,lz,arc\vehicle\darks\darks.fmi" "4Target\darks_e,lz,arc\vehicle\darks" /i /y
xcopy "2Source\darks_p,lz,arc\vehicle\darks\darks.fmi" "4Target\darks_p,lz,arc\vehicle\darks" /i /y
xcopy "2Source\dclaw_e,lz,arc\vehicle\dclaw\dclaw.fmi" "4Target\dclaw_e,lz,arc\vehicle\dclaw" /i /y
xcopy "2Source\dclaw_p,lz,arc\vehicle\dclaw\dclaw.fmi" "4Target\dclaw_p,lz,arc\vehicle\dclaw" /i /y
xcopy "2Source\fats_e,lz,arc\vehicle\fats\fats.fmi" "4Target\fats_e,lz,arc\vehicle\fats" /i /y
xcopy "2Source\fats_p,lz,arc\vehicle\fats\fats.fmi" "4Target\fats_p,lz,arc\vehicle\fats" /i /y
xcopy "2Source\fsting_e,lz,arc\vehicle\fsting\fsting.fmi" "4Target\fsting_e,lz,arc\vehicle\fsting" /i /y
xcopy "2Source\fsting_p,lz,arc\vehicle\fsting\fsting.fmi" "4Target\fsting_p,lz,arc\vehicle\fsting" /i /y
xcopy "2Source\gfox_e,lz,arc\vehicle\gfox\gfox.fmi" "4Target\gfox_e,lz,arc\vehicle\gfox" /i /y
xcopy "2Source\gfox_p,lz,arc\vehicle\gfox\gfox.fmi" "4Target\gfox_p,lz,arc\vehicle\gfox" /i /y
xcopy "2Source\gpan_e,lz,arc\vehicle\gpan\gpan.fmi" "4Target\gpan_e,lz,arc\vehicle\gpan" /i /y
xcopy "2Source\gpan_p,lz,arc\vehicle\gpan\gpan.fmi" "4Target\gpan_p,lz,arc\vehicle\gpan" /i /y
xcopy "2Source\gstar_e,lz,arc\vehicle\gstar\gstar.fmi" "4Target\gstar_e,lz,arc\vehicle\gstar" /i /y
xcopy "2Source\gstar_p,lz,arc\vehicle\gstar\gstar.fmi" "4Target\gstar_p,lz,arc\vehicle\gstar" /i /y
xcopy "2Source\gtaxi_e,lz,arc\vehicle\gtaxi\gtaxi.fmi" "4Target\gtaxi_e,lz,arc\vehicle\gtaxi" /i /y
xcopy "2Source\gtaxi_p,lz,arc\vehicle\gtaxi\gtaxi.fmi" "4Target\gtaxi_p,lz,arc\vehicle\gtaxi" /i /y
xcopy "2Source\hhawk_e,lz,arc\vehicle\hhawk\hhawk.fmi" "4Target\hhawk_e,lz,arc\vehicle\hhawk" /i /y
xcopy "2Source\hhawk_p,lz,arc\vehicle\hhawk\hhawk.fmi" "4Target\hhawk_p,lz,arc\vehicle\hhawk" /i /y
xcopy "2Source\hspeed_e,lz,arc\vehicle\hspeed\hspeed.fmi" "4Target\hspeed_e,lz,arc\vehicle\hspeed" /i /y
xcopy "2Source\hspeed_p,lz,arc\vehicle\hspeed\hspeed.fmi" "4Target\hspeed_p,lz,arc\vehicle\hspeed" /i /y
xcopy "2Source\itiger_e,lz,arc\vehicle\itiger\itiger.fmi" "4Target\itiger_e,lz,arc\vehicle\itiger" /i /y
xcopy "2Source\itiger_p,lz,arc\vehicle\itiger\itiger.fmi" "4Target\itiger_p,lz,arc\vehicle\itiger" /i /y
xcopy "2Source\kmete_e,lz,arc\vehicle\kmete\kmete.fmi" "4Target\kmete_e,lz,arc\vehicle\kmete" /i /y
xcopy "2Source\kmete_p,lz,arc\vehicle\kmete\kmete.fmi" "4Target\kmete_p,lz,arc\vehicle\kmete" /i /y
xcopy "2Source\lwy_e,lz,arc\vehicle\lwy\lwy.fmi" "4Target\lwy_e,lz,arc\vehicle\lwy" /i /y
xcopy "2Source\lwy_p,lz,arc\vehicle\lwy\lwy.fmi" "4Target\lwy_p,lz,arc\vehicle\lwy" /i /y
xcopy "2Source\mgull_e,lz,arc\vehicle\mgull\mgull.fmi" "4Target\mgull_e,lz,arc\vehicle\mgull" /i /y
xcopy "2Source\mgull_p,lz,arc\vehicle\mgull\mgull.fmi" "4Target\mgull_p,lz,arc\vehicle\mgull" /i /y
xcopy "2Source\mhurr_e,lz,arc\vehicle\mhurr\mhurr.fmi" "4Target\mhurr_e,lz,arc\vehicle\mhurr" /i /y
xcopy "2Source\mhurr_p,lz,arc\vehicle\mhurr\mhurr.fmi" "4Target\mhurr_p,lz,arc\vehicle\mhurr" /i /y
xcopy "2Source\mty_e,lz,arc\vehicle\mty\mty.fmi" "4Target\mty_e,lz,arc\vehicle\mty" /i /y
xcopy "2Source\mty_p,lz,arc\vehicle\mty\mty.fmi" "4Target\mty_p,lz,arc\vehicle\mty" /i /y
xcopy "2Source\mwolf_e,lz,arc\vehicle\mwolf\mwolf.fmi" "4Target\mwolf_e,lz,arc\vehicle\mwolf" /i /y
xcopy "2Source\mwolf_p,lz,arc\vehicle\mwolf\mwolf.fmi" "4Target\mwolf_p,lz,arc\vehicle\mwolf" /i /y
xcopy "2Source\nthun_e,lz,arc\vehicle\nthun\nthun.fmi" "4Target\nthun_e,lz,arc\vehicle\nthun" /i /y
xcopy "2Source\nthun_p,lz,arc\vehicle\nthun\nthun.fmi" "4Target\nthun_p,lz,arc\vehicle\nthun" /i /y
xcopy "2Source\pinks_e,lz,arc\vehicle\pinks\pinks.fmi" "4Target\pinks_e,lz,arc\vehicle\pinks" /i /y
xcopy "2Source\pinks_p,lz,arc\vehicle\pinks\pinks.fmi" "4Target\pinks_p,lz,arc\vehicle\pinks" /i /y
xcopy "2Source\prabbit_e,lz,arc\vehicle\prabbit\prabbit.fmi" "4Target\prabbit_e,lz,arc\vehicle\prabbit" /i /y
xcopy "2Source\prabbit_p,lz,arc\vehicle\prabbit\prabbit.fmi" "4Target\prabbit_p,lz,arc\vehicle\prabbit" /i /y
xcopy "2Source\qmete_e,lz,arc\vehicle\qmete\qmete.fmi" "4Target\qmete_e,lz,arc\vehicle\qmete" /i /y
xcopy "2Source\qmete_p,lz,arc\vehicle\qmete\qmete.fmi" "4Target\qmete_p,lz,arc\vehicle\qmete" /i /y
xcopy "2Source\rainp_e,lz,arc\vehicle\rainp\rainp.fmi" "4Target\rainp_e,lz,arc\vehicle\rainp" /i /y
xcopy "2Source\rainp_p,lz,arc\vehicle\rainp\rainp.fmi" "4Target\rainp_p,lz,arc\vehicle\rainp" /i /y
xcopy "2Source\rgaze_e,lz,arc\vehicle\rgaze\rgaze.fmi" "4Target\rgaze_e,lz,arc\vehicle\rgaze" /i /y
xcopy "2Source\rgaze_p,lz,arc\vehicle\rgaze\rgaze.fmi" "4Target\rgaze_p,lz,arc\vehicle\rgaze" /i /y
xcopy "2Source\rrock_e,lz,arc\vehicle\rrock\rrock.fmi" "4Target\rrock_e,lz,arc\vehicle\rrock" /i /y
xcopy "2Source\rrock_p,lz,arc\vehicle\rrock\rrock.fmi" "4Target\rrock_p,lz,arc\vehicle\rrock" /i /y
xcopy "2Source\sang_e,lz,arc\vehicle\sang\sang.fmi" "4Target\sang_e,lz,arc\vehicle\sang" /i /y
xcopy "2Source\sang_p,lz,arc\vehicle\sang\sang.fmi" "4Target\sang_p,lz,arc\vehicle\sang" /i /y
xcopy "2Source\scarp_e,lz,arc\vehicle\scarp\scarp.fmi" "4Target\scarp_e,lz,arc\vehicle\scarp" /i /y
xcopy "2Source\scarp_p,lz,arc\vehicle\scarp\scarp.fmi" "4Target\scarp_p,lz,arc\vehicle\scarp" /i /y
xcopy "2Source\smoon_e,lz,arc\vehicle\smoon\smoon.fmi" "4Target\smoon_e,lz,arc\vehicle\smoon" /i /y
xcopy "2Source\smoon_p,lz,arc\vehicle\smoon\smoon.fmi" "4Target\smoon_p,lz,arc\vehicle\smoon" /i /y
xcopy "2Source\sphan_e,lz,arc\vehicle\sphan\sphan.fmi" "4Target\sphan_e,lz,arc\vehicle\sphan" /i /y
xcopy "2Source\sphan_p,lz,arc\vehicle\sphan\sphan.fmi" "4Target\sphan_p,lz,arc\vehicle\sphan" /i /y
xcopy "2Source\spira_e,lz,arc\vehicle\spira\spira.fmi" "4Target\spira_e,lz,arc\vehicle\spira" /i /y
xcopy "2Source\spira_p,lz,arc\vehicle\spira\spira.fmi" "4Target\spira_p,lz,arc\vehicle\spira" /i /y
xcopy "2Source\srat_e,lz,arc\vehicle\srat\srat.fmi" "4Target\srat_e,lz,arc\vehicle\srat" /i /y
xcopy "2Source\srat_p,lz,arc\vehicle\srat\srat.fmi" "4Target\srat_p,lz,arc\vehicle\srat" /i /y
xcopy "2Source\tnori_e,lz,arc\vehicle\tnori\tnori.fmi" "4Target\tnori_e,lz,arc\vehicle\tnori" /i /y
xcopy "2Source\tnori_p,lz,arc\vehicle\tnori\tnori.fmi" "4Target\tnori_p,lz,arc\vehicle\tnori" /i /y
xcopy "2Source\wboar_e,lz,arc\vehicle\wboar\wboar.fmi" "4Target\wboar_e,lz,arc\vehicle\wboar" /i /y
xcopy "2Source\wboar_p,lz,arc\vehicle\wboar\wboar.fmi" "4Target\wboar_p,lz,arc\vehicle\wboar" /i /y
xcopy "2Source\wcat_e,lz,arc\vehicle\wcat\wcat.fmi" "4Target\wcat_e,lz,arc\vehicle\wcat" /i /y
xcopy "2Source\wcat_p,lz,arc\vehicle\wcat\wcat.fmi" "4Target\wcat_p,lz,arc\vehicle\wcat" /i /y
xcopy "2Source\wgoose_e,lz,arc\vehicle\wgoose\wgoose.fmi" "4Target\wgoose_e,lz,arc\vehicle\wgoose" /i /y
xcopy "2Source\wgoose_p,lz,arc\vehicle\wgoose\wgoose.fmi" "4Target\wgoose_p,lz,arc\vehicle\wgoose" /i /y
xcopy "2Source\wwasp_e,lz,arc\vehicle\wwasp\wwasp.fmi" "4Target\wwasp_e,lz,arc\vehicle\wwasp" /i /y
xcopy "2Source\wwasp_p,lz,arc\vehicle\wwasp\wwasp.fmi" "4Target\wwasp_p,lz,arc\vehicle\wwasp" /i /y
gxpand pack 4Target 5FinalOutput

pause